-- NARMSCENTER
INSERT INTO NARMSCENTER (ID,CenterName,CenterState) VALUES(1,'California','California');
INSERT INTO NARMSCENTER (ID,CenterName,CenterState) VALUES(2,'Colorado','Colorado');
INSERT INTO NARMSCENTER (ID,CenterName,CenterState) VALUES(3,'Connecticut','Connecticut');
INSERT INTO NARMSCENTER (ID,CenterName,CenterState) VALUES(4,'Washington','Washington');

-- CenterMeatTypeLimit 1
INSERT INTO CenterMeatTypeLimit (ID,totalLimit,type,narms_center_id) VALUES(1,40,'Chicken',1);
INSERT INTO CenterMeatTypeLimit (ID,totalLimit,type,narms_center_id) VALUES(2,10,'Beef',1);
INSERT INTO CenterMeatTypeLimit (ID,totalLimit,type,narms_center_id) VALUES(3,20,'Turkey',1);
INSERT INTO CenterMeatTypeLimit (ID,totalLimit,type,narms_center_id) VALUES(4,10,'Pork',1);

-- CenterMeatTypeLimit 2
INSERT INTO CenterMeatTypeLimit (ID,totalLimit,type,narms_center_id) VALUES(5,40,'Chicken',2);
INSERT INTO CenterMeatTypeLimit (ID,totalLimit,type,narms_center_id) VALUES(6,10,'Beef',2);
INSERT INTO CenterMeatTypeLimit (ID,totalLimit,type,narms_center_id) VALUES(7,20,'Turkey',2);
INSERT INTO CenterMeatTypeLimit (ID,totalLimit,type,narms_center_id) VALUES(8,10,'Pork',2);


INSERT INTO CenterMeatTypeLimit (ID,totalLimit,type,narms_center_id) VALUES(9,40,'Chicken',3);
INSERT INTO CenterMeatTypeLimit (ID,totalLimit,type,narms_center_id) VALUES(10,10,'Beef',3);
INSERT INTO CenterMeatTypeLimit (ID,totalLimit,type,narms_center_id) VALUES(11,20,'Turkey',3);
INSERT INTO CenterMeatTypeLimit (ID,totalLimit,type,narms_center_id) VALUES(12,10,'Pork',3);

INSERT INTO CenterMeatTypeLimit (ID,totalLimit,type,narms_center_id) VALUES(13,40,'Chicken',4);
INSERT INTO CenterMeatTypeLimit (ID,totalLimit,type,narms_center_id) VALUES(14,10,'Beef',4);
INSERT INTO CenterMeatTypeLimit (ID,totalLimit,type,narms_center_id) VALUES(15,20,'Turkey',4);
INSERT INTO CenterMeatTypeLimit (ID,totalLimit,type,narms_center_id) VALUES(16,10,'Pork',4);

-- narms_store
INSERT INTO narms_store (ID,store_name,store_address,narms_center_id) VALUES(1,'Walmart','California Street 1',1);
INSERT INTO narms_store (ID,store_name,store_address,narms_center_id) VALUES(2,'Target','California Street 2',1);
INSERT INTO narms_store (ID,store_name,store_address,narms_center_id) VALUES(3,'Giant','California Street 3',1);

INSERT INTO narms_store (ID,store_name,store_address,narms_center_id) VALUES(4,'Walmart','Maryland Street 1',2);
INSERT INTO narms_store (ID,store_name,store_address,narms_center_id) VALUES(5,'Target','Maryland Street 2',2);
INSERT INTO narms_store (ID,store_name,store_address,narms_center_id) VALUES(6,'Giant','Maryland Street 3',2);


INSERT INTO narms_store (ID,store_name,store_address,narms_center_id) VALUES(7,'Walmart','DC Street 1',3);
INSERT INTO narms_store (ID,store_name,store_address,narms_center_id) VALUES(8,'Target','DC Street 2',3);
INSERT INTO narms_store (ID,store_name,store_address,narms_center_id) VALUES(9,'Giant','DC Street 3',3);

INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (10,'99 Ranch Market','22511 Highway 99 Ste 108 EDMONDS, WA 98026-8398',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (11,'ABC Market','2500 Beacon Ave S SEATTLE, WA 98144-5126',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (12,'Albertsons','15100 SE 38th St Ste 103 BELLEVUE, WA 98006-1763',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (13,'Albertsons','16304 Bothell Everett Hwy MILL CREEK, WA 98012-1293',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (14,'Albertsons','3322 132nd St SE MILL CREEK, WA 98012-5654',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (15,'Albertsons','19500 Highway 99 Ste 110 LYNNWOOD, WA 98036-5291',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (16,'Albertsons','4301 212th St SW MOUNTLAKE TERRACE, WA 98043-3585',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (17,'Albertsons','4621 NE Sunset Blvd RENTON, WA 98059-4096',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (18,'Albertsons','12811 Beverly Park Rd LYNNWOOD, WA 98087-5126',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (19,'Albertsons','13050 Aurora Ave N SEATTLE, WA 98133-7507',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (20,'Albertsons','2550 32nd Ave W SEATTLE, WA 98199-3220',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (21,'Albertsons','6727 Evergreen Way EVERETT, WA 98203-4551',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (22,'Albertsons','520 128th St SW Ste C2 EVERETT, WA 98204-9351',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (23,'Ballard Market','1400 NW 56th St SEATTLE, WA 98107-3799',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (24,'Boulevard Park Thriftway','12000 Des Moines Memorial Dr S SEATTLE, WA 98168-2228',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (25,'Central Market Hill Creek','15605 Main St MILL CREEK, WA 98012-7373',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (26,'Central Market Shoreline','15505 Westminster Way N SHORELINE, WA 98133-5927',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (27,'Costco Wholesale','8629 120th Ave NE KIRKLAND, WA 98033-5865',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (28,'Costco Wholesale','18109 33rd Ave W LYNNWOOD, WA 98037-4840',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (29,'Costco Wholesale','24008 Snohomish Woodinville Rd WOODINVILLE, WA 98072-9743',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (30,'Costco Wholesale','1175 N 205th St SHORELINE, WA 98133-3206',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (31,'Costco Wholesale','4401 4th Ave S SEATTLE, WA 98134-2389',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (32,'Costco Wholesale','10200 19th Ave SE EVERETT, WA 98208-4256',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (33,'Dominic\'s Red Apple','9627 Des Moines Memorial Dr SEATTLE, WA 98108-5033',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (34,'Edmonds IGA Market','550 5th Ave S EDMONDS, WA 98020-3403',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (35,'Fred Meyer','2041 148th Ave NE BELLEVUE, WA 98007-3788',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (36,'Fred Meyer','21045 Bothell Everett Hwy BOTHELL, WA 98021-8405',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (37,'Fred Meyer','12221 120th Ave NE KIRKLAND, WA 98034-6905',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (38,'Fred Meyer','4615 196th St SW Ste 175 LYNNWOOD, WA 98036-5596',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (39,'Fred Meyer','17667 NE 76th St REDMOND, WA 98052-4994',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (40,'Fred Meyer','365 Renton Center Way SW Ste D RENTON, WA 98057-2324',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (41,'Fred Meyer','2902 164th St SW Ste A LYNNWOOD, WA 98087-3201',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (42,'Fred Meyer','915 NW 45th St SEATTLE, WA 98107-4606',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (43,'Fred Meyer','100 NW 85th St Unit Main SEATTLE, WA 98117-3058',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (44,'Fred Meyer','13000 Lake City Way NE SEATTLE, WA 98125-4429',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (45,'Fred Meyer','18325 Aurora Ave N SHORELINE, WA 98133-4496',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (46,'Fred Meyer','14300 1st Ave S Ste 3 BURIEN, WA 98168-3490',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (47,'Fred Meyer','8530 Evergreen Way Unit Main EVERETT, WA 98208-2652',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (48,'Fred Meyer','12906 Bothell Everett Hwy EVERETT, WA 98208-6688',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (49,'Grocery Outlet','15625 NE 8th St Ste E BELLEVUE, WA 98008-3943',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (50,'Grocery Outlet','7800 NE Bothell Way Ste 140 KENMORE, WA 98028-1830',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (51,'Grocery Outlet','19800 44th Ave W Ste G LYNNWOOD, WA 98036-6739',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (52,'Grocery Outlet','2809 NE Sunset Blvd RENTON, WA 98056-3105',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (53,'Grocery Outlet','8700 15th Ave NW SEATTLE, WA 98117-3501',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (54,'Grocery Outlet','1126 Martin Luther King Jr Way SEATTLE, WA 98122-5052',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (55,'Grocery Outlet','3020 NE 127th St SEATTLE, WA 98125-4415',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (56,'Grocery Outlet','13201 Aurora Ave N Unit Main SEATTLE, WA 98133-7586',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (57,'Grocery Outlet','1702 4th Ave S SEATTLE, WA 98134-1502',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (58,'Grocery Outlet','11656 68th Ave S SEATTLE, WA 98178-2916',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (59,'Grocery Outlet','710 SE Everett Mall Way EVERETT, WA 98208-3732',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (60,'H Mart','100 108th Ave NE Ste A BELLEVUE, WA 98004-5970',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (61,'Haggen Northwest Fresh','17641 Garden Way NE WOODINVILLE, WA 98072-3535',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (62,'Haggen Northwest Fresh','7171 Bothell Way Ne LAKE FOREST PARK, WA 98155',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (63,'Haggen Northwest Fresh','17520 State Route 9 SE SNOHOMISH, WA 98296-8320',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (64,'Hilltop Red Apple Market','2701 Beacon Ave S SEATTLE, WA 98144-5127',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (65,'Hop-In Market','2605 22nd Ave E SEATTLE, WA 98112-2217',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (66,'Madison Market Central Co-Op','1600 E Madison St SEATTLE, WA 98122-2731',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (67,'Marketime Foods','4416 Fremont Ave N SEATTLE, WA 98103-7226',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (68,'Matthew\'s Fresh Market','4989 Lakemont Blvd SE BELLEVUE, WA 98006-7803',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (69,'Metropolitan Market','10611 NE 68th St KIRKLAND, WA 98033-7054',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (70,'Metropolitan Market','5250 40th Ave NE SEATTLE, WA 98105-3045',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (71,'Metropolitan Market','100 Mercer St SEATTLE, WA 98109-4008',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (72,'Metropolitan Market','2320 42nd Ave SW SEATTLE, WA 98116-2535',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (73,'Metropolitan Market','3830 34th Ave W SEATTLE, WA 98199-1628',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (74,'PCC Natural Markets','9803 Edmonds Way EDMONDS, WA 98020-5901',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (75,'PCC Natural Markets','10718 NE 68th St KIRKLAND, WA 98033-7030',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (76,'PCC Natural Markets','11435 Avondale Rd NE REDMOND, WA 98052',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (77,'PCC Natural Markets','7504 Aurora Ave N SEATTLE, WA 98103-4748',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (78,'PCC Natural Markets','600 N 34th St SEATTLE, WA 98103-8604',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (79,'PCC Natural Markets','450 NE 71st St SEATTLE, WA 98115-5464',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (80,'PCC Natural Markets','6514 40th Ave NE SEATTLE, WA 98115-7530',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (81,'PCC Natural Markets','2749 California Ave SW SEATTLE, WA 98116-2405',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (82,'PCC Natural Markets','5041 Wilson Ave S SEATTLE, WA 98118-2084',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (83,'PCC Natural Markets','3610 S Edmunds St SEATTLE, WA 98118-2178',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (84,'Promenade Red Apple','2301 S Jackson St Ste C SEATTLE, WA 98144-2357',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (85,'Quality Food Center','10116 NE 8th St BELLEVUE, WA 98004',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (86,'Quality Food Center','2636 Bellevue Way NE BELLEVUE, WA 98004-2209',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (87,'Quality Food Center','3550 Factoria Blvd SE BELLEVUE, WA 98006-6126',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (88,'Quality Food Center','1510 145th Pl SE BELLEVUE, WA 98007',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (89,'Quality Food Center','15600 NE 8th St Ste K1 BELLEVUE, WA 98008-3999',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (90,'Quality Food Center','18921 Bothell Way NE BOTHELL, WA 98011-1934',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (91,'Quality Food Center','926 164th St SE MILL CREEK, WA 98012-6305',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (92,'Quality Food Center','22828 100th Ave W EDMONDS, WA 98020-5920',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (93,'Quality Food Center','22833 Bothell Everett Hwy BOTHELL, WA 98021',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (94,'Quality Food Center','211 Parkplace Ctr KIRKLAND, WA 98033-6228',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (95,'Quality Food Center','14130 Juanita Dr NE KIRKLAND, WA 98034',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (96,'Quality Food Center','11224 NE 124th St KIRKLAND, WA 98034-4301',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (97,'Quality Food Center','7500 196th St SW Ste B LYNNWOOD, WA 98036-5090',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (98,'Quality Food Center','17525 Highway 99 Ste F LYNNWOOD, WA 98037-3105',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (99,'Quality Food Center','7823 SE 28th St MERCER ISLAND, WA 98040-2902',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (100,'Quality Food Center','8421 SE 68th St MERCER ISLAND, WA 98040-5235',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (101,'Quality Food Center','22803 44th Ave W MOUNTLAKE TERRACE, WA 98043',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (102,'Quality Food Center','8867 161st Ave NE REDMOND, WA 98052',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (103,'Quality Food Center','15800 Redmond Way REDMOND, WA 98052-3829',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (104,'Quality Food Center','6940 Coal Creek Pkwy SE NEWCASTLE, WA 98059-3137',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (105,'Quality Food Center','4800 NE 4th St RENTON, WA 98059-4820',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (106,'Quality Food Center','417 Broadway E Ste 2 SEATTLE, WA 98102',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (107,'Quality Food Center','1801 N 45th St SEATTLE, WA 98103-6859',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (108,'Quality Food Center','2746 NE 45th St Ste 2 SEATTLE, WA 98105-5017',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (109,'Quality Food Center','5700 24th Ave NW SEATTLE, WA 98107-3203',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (110,'Quality Food Center','500 Mercer St SEATTLE, WA 98109',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (111,'Quality Food Center','416 15th Ave E SEATTLE, WA 98112-4505',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (112,'Quality Food Center','8400 35th Ave NE SEATTLE, WA 98115-4819',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (113,'Quality Food Center','4550 42nd Ave SW SEATTLE, WA 98116-4225',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (114,'Quality Food Center','9999 Holman Rd NW SEATTLE, WA 98117-2099',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (115,'Quality Food Center','1600 W Dravus St SEATTLE, WA 98119-1721',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (116,'Quality Food Center','1401 Broadway SEATTLE, WA 98122-3854',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (117,'Quality Food Center','11100 Roosevelt Way NE SEATTLE, WA 98125-6234',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (118,'Quality Food Center','2500 SW Barton St SEATTLE, WA 98126',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (119,'Quality Food Center','2707 Rainier Ave S SEATTLE, WA 98144-5332',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (120,'Quality Food Center','1531 NE 145th St SEATTLE, WA 98155-7205',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (121,'Quality Food Center','600 NW Richmond Beach Rd SHORELINE, WA 98177-3122',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (122,'Quality Food Center','4919 Evergreen Way EVERETT, WA 98203-2828',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (123,'Quality Food Center','11700 Mukilteo Speedway Ste 300 MUKILTEO, WA 98275-5436',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (124,'Saar\'s Market Place','3208 NE Sunset Blvd RENTON, WA 98056-3335',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (125,'Saar\'s Market Place','9000 Rainier Ave S SEATTLE, WA 98118',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (126,'Safeway','300 Bellevue Way NE BELLEVUE, WA 98004-5718',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (127,'Safeway','1645 140th Ave NE Ste A5 BELLEVUE, WA 98005-2320',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (128,'Safeway','3903 Factoria Blvd SE BELLEVUE, WA 98006-6148',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (129,'Safeway','13314 Bothell Everett Hwy MILL CREEK, WA 98012-5509',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (130,'Safeway','20711 Bothell Everett Hwy BOTHELL, WA 98012-7139',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (131,'Safeway','24040 Bothell Everett Hwy BOTHELL, WA 98021-9342',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (132,'Safeway','23632 Highway 99 Ste L EDMONDS, WA 98026-9206',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (133,'Safeway','6850 NE Bothell Way Ste Main KENMORE, WA 98028-2404',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (134,'Safeway','12519 NE 85th St KIRKLAND, WA 98033-8048',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (135,'Safeway','14444 124th Ave NE KIRKLAND, WA 98034-4801',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (136,'Safeway','10020 NE 137th St KIRKLAND, WA 98034-5221',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (137,'Safeway','19715 Highway 99 LYNNWOOD, WA 98036-6039',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (138,'Safeway','17246 Redmond Way REDMOND, WA 98052-4403',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (139,'Safeway','15000 NE 24th St REDMOND, WA 98052-5531',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (140,'Safeway','2725 NE Sunset Blvd RENTON, WA 98056-3137',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (141,'Safeway','200 S 3rd St Ste B RENTON, WA 98057-2031',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (142,'Safeway','6911 Coal Creek Pkwy SE NEWCASTLE, WA 98059-3136',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (143,'Safeway','19150 NE Woodinville Duvall Rd Ste A1 WOODINVILLE, WA 98077-9477',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (144,'Safeway','14826 Highway 99 LYNNWOOD, WA 98087-2322',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (145,'Safeway','8704 Greenwood Ave N SEATTLE, WA 98103-3616',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (146,'Safeway','4732 Brooklyn Ave NE SEATTLE, WA 98105-4411',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (147,'Safeway','3020 NE 45th St SEATTLE, WA 98105-5002',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (148,'Safeway','1423 NW Market St SEATTLE, WA 98107-3744',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (149,'Safeway','2100 Queen Anne Ave N SEATTLE, WA 98109-2309',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (150,'Safeway','1410 E John St SEATTLE, WA 98112-5218',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (151,'Safeway','2201 E Madison St SEATTLE, WA 98112-5336',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (152,'Safeway','7300 Roosevelt Way NE Unit Main SEATTLE, WA 98115-5663',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (153,'Safeway','7340 35th Ave NE SEATTLE, WA 98115-5919',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (154,'Safeway','2622 California Ave SW SEATTLE, WA 98116-2459',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (155,'Safeway','4754 42nd Ave SW SEATTLE, WA 98116-4553',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (156,'Safeway','8340 15th Ave NW SEATTLE, WA 98117-3603',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (157,'Safeway','3820 Rainier Ave S Unit Main SEATTLE, WA 98118-1100',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (158,'Safeway','3900 S Othello St SEATTLE, WA 98118-3543',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (159,'Safeway','9262 Rainier Ave S SEATTLE, WA 98118-5570',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (160,'Safeway','516 1st Ave W SEATTLE, WA 98119-3926',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (161,'Safeway','12318 15th Ave NE SEATTLE, WA 98125-4820',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (162,'Safeway','9620 28th Ave SW SEATTLE, WA 98126-4102',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (163,'Safeway','17202 15th Ave NE SHORELINE, WA 98155-5130',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (164,'Safeway','4128 Rucker Ave EVERETT, WA 98203-2211',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (165,'Safeway','11031 19th Ave SE EVERETT, WA 98208-5144',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (166,'Safeway','5802 134th Pl SE EVERETT, WA 98208-9426',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (167,'Sam\'s Club','901 S Grady Way RENTON, WA 98057-3226',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (168,'Sam\'s Club','13550 Aurora Ave N SEATTLE, WA 98133-7512',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (169,'Saveway Market','109 Occidental Ave S SEATTLE, WA 98104-2517',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (170,'Super Saver Foods','10616 16th Ave SW SEATTLE, WA 98146-2076',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (171,'Super Saver Foods','3725 S 144th St TUKWILA, WA 98168-4044',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (172,'Target PFresh','4053 Factoria Square Mall SE BELLEVUE, WA 98006-1200',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (173,'Target PFresh','18305 Alderwood Mall Pkwy LYNNWOOD, WA 98037-3961',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (174,'Target PFresh','17700 NE 76th St REDMOND, WA 98052-3300',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (175,'Target PFresh','1215 N Landing Way RENTON, WA 98057-5521',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (176,'Target PFresh','13950 NE 178th Pl Ste 100 WOODINVILLE, WA 98072-3523',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (177,'Target PFresh','302 NE Northgate Way SEATTLE, WA 98125-6047',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (178,'Target PFresh','2800 SW Barton St SEATTLE, WA 98126-3990',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (179,'Target PFresh','405 SE Everett Mall Way EVERETT, WA 98208-3200',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (180,'Total Wine & More','699 120th Ave NE BELLEVUE, WA 98005-3009',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (181,'Total Wine & More','2701 184th St SW Ste 108 LYNNWOOD, WA 98037-4739',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (182,'Total Wine & More','525 NE Northgate Way Ste 5 SEATTLE, WA 98125',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (183,'Trader Joe\'s','15563 NE 24th St BELLEVUE, WA 98007-3836',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (184,'Trader Joe\'s','12632 120th Ave NE KIRKLAND, WA 98034-7502',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (185,'Trader Joe\'s','19500 Highway 99 Ste 100 LYNNWOOD, WA 98036-5241',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (186,'Trader Joe\'s','15932 Redmond Way REDMOND, WA 98052',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (187,'Trader Joe\'s','4555 Roosevelt Way NE SEATTLE, WA 98105',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (188,'Trader Joe\'s','4609 14th Ave NW Ste 101 SEATTLE, WA 98107-4619',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (189,'Trader Joe\'s','1916 Queen Anne Ave N SEATTLE, WA 98109-2548',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (190,'Trader Joe\'s','1700 E Madison St Ste 100 SEATTLE, WA 98122-7008',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (191,'Trader Joe\'s','4545 Fauntleroy Way SW SEATTLE, WA 98126-2739',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (192,'Trader Joe\'s','1201 N 175th St SHORELINE, WA 98133-5064',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (193,'Trader Joe\'s','811 SE Everett Mall Way Ste B EVERETT, WA 98208-3761',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (194,'Uwajimaya','699 120th Ave NE BELLEVUE, WA 98005-3009',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (195,'Uwajimaya','501 S Grady Way RENTON, WA 98057-3211',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (196,'Uwajimaya','600 5th Ave S Ste 100 SEATTLE, WA 98104-3898',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (197,'Village Thriftway','20150 Ballinger Way NE SHORELINE, WA 98155-1117',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (198,'Walmart Neighborhood Market','15063 Main St BELLEVUE, WA 98007-5225',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (199,'Walmart Neighborhood Market','17222 Highway 99 LYNNWOOD, WA 98037-3170',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (200,'Walmart Supercenter','1605 SE Everett Mall Way EVERETT, WA 98208-2838',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (201,'Whole Foods Market','888 116th Ave NE BELLEVUE, WA 98004-4607',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (202,'Whole Foods Market','2800 196th St SW LYNNWOOD, WA 98036-6923',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (203,'Whole Foods Market','17991 Redmond Way REDMOND, WA 98052-4907',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (204,'Whole Foods Market','1026 NE 64th St SEATTLE, WA 98115-6656',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (205,'Whole Foods Market','2001 15th Ave W SEATTLE, WA 98119-2768',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (206,'Whole Foods Market','2210 Westlake Ave SEATTLE, WA 98121-2713',4);
INSERT INTO narms_store (ID, store_name, store_address, narms_center_id) VALUES (207,'WinCo Foods','9900 19th Ave SE EVERETT, WA 98208-3811',4);

-- narms_brand
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (1,'AA','ALBERTSONS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (2,'AB','ALLEN FAMILY FOODS/ALLENS ALL NATURAL/ALLEN HARIM');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (3,'AC','AMISH SELECT');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (4,'AD','ANGUS MEATS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (5,'AE','ARCHER FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (6,'AF','ARMOUR');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (7,'AAR','365 EVERYDAY VALUE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (8,'AAA','COUNTRY PRIDE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (9,'AAB','GRAYSON NATURAL FARMS ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (10,'AAC','TOMER KOSHER FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (11,'AAD','SIGNATURE FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (12,'AAE','BEST MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (13,'AAF','PAUL\'S SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (14,'AAG','YOUNG & TENDER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (15,'AAH','NATURE\'S FINEST');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (16,'AAI','TOP BEE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (17,'AAJ','SIMPLE CREATIONS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (18,'AAK','SUPER MERCADO MI TIERRA');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (19,'AAL','RALEY\'S DAILIES');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (20,'AAM','NORBEST');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (21,'AAN','ROBERT FRESH MARKET ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (22,'AAO','STAR RANCH ANGUS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (23,'AAP','SHOR HABOR');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (24,'AAQ','PINELAND FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (25,'AG','B3R COUNTRY MEATS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (26,'AH','BELL & EVANS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (27,'AI','BELL MARKETS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (28,'AJ','BEYOND BELIEF');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (29,'AK','BILL MARTINS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (30,'AL','BIRCHWOOD FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (31,'AM','BJS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (32,'AN','BOBS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (33,'AO','BOTTO\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (34,'AP','BROOKDALE FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (35,'AQ','BUTTERBALL');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (36,'AR','BYERLY\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (37,'AS','CALA FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (38,'AT','CALABELL STORES');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (39,'AU','CAROLINA TURKEY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (40,'AV','CATTELMANS COLLECTION');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (41,'AW','CEEBEE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (42,'AX','CENTURY FARM');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (43,'AY','CHEFS CHOICE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (44,'AZ','CLAXTON');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (45,'BA','COASTAL RANGE ORGANICS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (46,'BB','COLEMAN NATURAL ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (47,'BC','CONAGRA');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (48,'BD','CUB FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (49,'BE','DIESTEL');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (50,'BF','DU BRETON');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (51,'BG','EBERLYS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (52,'BH','EDS IGA');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (53,'BI','EMPIRE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (54,'BJ','EXCEL');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (55,'BK','FAIR N SQUARE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (56,'BL','FAIRBANKS FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (57,'BM','FARMLAND');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (58,'BN','FARMLAND FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (59,'BO','FESTIVAL FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (60,'BP','FESTIVE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (61,'BQ','FIELDALE FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (62,'BR','FOOD DEPOT');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (63,'BS','FOOD LION');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (64,'BT','FOODLAND');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (65,'BU','FOSTER FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (66,'BV','FRED MEYER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (67,'BW','FRESNO MEAT CO');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (68,'BX','GERBER POULTRY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (69,'BY','GIANT');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (70,'BZ','GNC EMPORIUM');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (71,'CA','GOLD N PLUMP');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (72,'CB','GOLDKIST');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (73,'CC','GOURMET CREATIONS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (74,'CD','GREEN VALLEY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (75,'CE','HAGGEN / HAGGEN PHARMACY AND DRUG');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (76,'CF','HANNAFORD');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (77,'CG','HANSON P0ULTRY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (78,'CH','HARRIS TEETER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (79,'CI','HATFIELD');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (80,'CJ','HG HILL');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (81,'CK','HONEYSUCKLE WHITE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (82,'CL','HORMEL');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (83,'CM','IBP');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (84,'CN','IDEAL FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (85,'CO','INGLES');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (86,'CP','INTER-AMERICAN PRODUCTS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (87,'CQ','INTERSTATE MEAT');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (88,'CR','JENNIE-O TURKEY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (89,'CS','JOHN MORRELL');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (90,'CT','JUBILEE FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (91,'CU','KADEJAN');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (92,'CV','KEINDELS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (93,'CW','KING SOOPERS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (94,'CX','KLEINS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (95,'CY','KOWALSKI\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (96,'CZ','KROGER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (97,'DA','LAURA\'S LEAN BEEF (LAURA\'S BEEF)');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (98,'DB','MANOR HOUSE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (99,'DC','MARS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (100,'DD','MASTER CHOICE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (101,'DE','MAVERICK');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (102,'DF','MAVERICK RANCH');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (103,'DG','MBA BRAND SMART CHICKEN');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (104,'DH','METRO');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (105,'DI','MEYER ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (106,'DJ','MIDWEST PRIDE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (107,'DK','MILLER AMISH COUNTRY POULTRY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (108,'DL','MORAN\'S GROUND BEEF');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (109,'DM','MURRAY\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (110,'DN','NATURAL Y CHICKEN');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (111,'DO','NATURE\'S PLACE (NATURE\'S PLACE, ALL NATURAL)');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (112,'DP','NOB HILL FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (113,'DQ','NORTHWEST FINEST');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (114,'DR','NORTHWEST GROWN');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (115,'DS','PENNEXX FOOD');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (116,'DT','PENNFIELD FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (117,'DU','PERDUE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (118,'DV','PIGGLY WIGGLY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (119,'DW','PILGRIMS\' PRIDE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (120,'DX','PLAINVILLE FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (121,'DY','PORTERS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (122,'DZ','PRAIRIE FRESH');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (123,'EA','PREMIUM PORK');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (124,'EB','PRESTIGE MEATS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (125,'EC','PRICE CHOPPER ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (126,'ED','PUBLIX');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (127,'EE','QUALITY FOOD CENTER (QFC)');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (128,'EF','QUALITY FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (129,'EG','RAINBOW');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (130,'EH','RALEY\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (131,'EI','RALPH\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (132,'EJ','REDBIRD');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (133,'EK','ROCKY THE FREE-RANGE CHICKEN');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (134,'EL','ROSIE THE ORGANIC CHICKEN/ROSIE FREE RANGE CHICKEN');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (135,'EM','ROUNDY\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (136,'EN','RUBASHKINS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (137,'EO','SAFEWAY / SAFEWAY FARMS ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (138,'EP','SANDERSON FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (139,'EQ','SANTONI\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (140,'ER','SAVE RITE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (141,'ES','SHADY BROOK FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (142,'ET','SHAPIRO');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (143,'EU','SHENANDOAH');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (144,'EV','SHOPPERS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (145,'EW','SILVER PLATTER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (146,'EX','SILVER T');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (147,'EY','SMITHFIELD');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (148,'EZ','SMITH\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (149,'FA','SODERQUIST MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (150,'FB','SONOMA FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (151,'FC','SOUTHERN GROWN');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (152,'FD','SPRINGERHILL RANCH');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (153,'FE','SPRINGER MOUNTAIN FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (154,'FF','STERLING STORE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (155,'FG','SUNFLOWER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (156,'FH','SUPER FRESH');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (157,'FI','SUPER G');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (158,'FJ','SUPER KMART');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (159,'FK','SUPREME');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (160,'FL','SUREBEAM');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (161,'FM','SWIFT');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (162,'FN','TARGET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (163,'FO','THE BUTCHERS BLOCK, INC.');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (164,'FP','THE BUTCHERS CUT');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (165,'FQ','THOMAS E. WILSON');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (166,'FR','TOWER MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (167,'FS','TYSON');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (168,'FT','VALCHRIS FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (169,'FU','WAKEFERN FOOD CORP');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (170,'FV','WALMART');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (171,'FW','WAMPLER FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (172,'FX','WAYBEST FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (173,'FY','WAYFIELD');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (174,'FZ','WEIS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (175,'GA','WELLINGTON FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (176,'GB','WHITE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (177,'GC','WHITE GEM');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (178,'GD','WHOLE FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (179,'GE','WILD HARVEST');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (180,'GF','WILD OATS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (181,'GG','WINCO FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (182,'GH','WINN-DIXIE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (183,'GI','WOLFES NECK FARM');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (184,'GJ','ZACKY FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (185,'GK','ZUPAN\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (186,'GL','HARRIS RANCH');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (187,'GM','RANGER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (188,'GN','CARLTON FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (189,'GO','CERTIFIED ANGUS BEEF BRAND');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (190,'GP','DRAPER VALLEY FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (191,'GQ','ST FRANCIS FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (192,'GR','SMART CHICKEN');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (193,'GS','SHELTON\'S ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (194,'GT','WHOLE FARM COOP');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (195,'GU','PREMIUM STANDARD FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (196,'GV','ROUSES SUPERMARKET ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (197,'GW','ANGUS PRIDE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (198,'GX','ORGANIC PRARIE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (199,'GY','LUNDS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (200,'GZ','ECONO FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (201,'HA','TRADER JOES BUTCHER SHOP');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (202,'HB','FULTON FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (203,'HC','RANCHERS RESERVE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (204,'HD','ANDRONICO\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (205,'HE','PW MARKETS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (206,'HF','HILL MEAT CO');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (207,'HG','FRIENDLY VILLAGE MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (208,'HH','BUTCHER\'S BRAND');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (209,'HI','GRAUL\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (210,'HJ','EMPIRE KOSHER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (211,'HK','BUTCHER\'S RESERVE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (212,'HL','MOUNTAIRE FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (213,'HM','BEELER\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (214,'HN','HI-LO');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (215,'HO','JOHN BROOKS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (216,'HP','LOUIS RICH');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (217,'HQ','LOWE\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (218,'HR','NATURAL CHOICE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (219,'HS','PRICE RITE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (220,'HT','RALEY\'S PREMIUM');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (221,'HU','ROCKY JUNIOR');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (222,'HV','STADIUM MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (223,'HW','TRADER JOES AARON\'S BEST');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (224,'HX','IGA');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (225,'HY','MOIST & TENDER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (226,'HZ','FOODS CO.');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (227,'IA','SUNSET SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (228,'IB','PACIFIC SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (229,'IC','NATURAL PORK /FALLS BRAND NATURAL PORK');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (230,'ID','NATUREWELL');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (231,'IE','GREAT VALUE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (232,'IF','STOP SHOP & SAVE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (233,'IG','CARGILL');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (234,'IH','99 RANCH MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (235,'II','TURKEY SELECTS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (236,'IJ','SAVEMART');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (237,'IK','SEVEN MILE MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (238,'IL','THE MARKETS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (239,'IM','JUST PERFECT');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (240,'IN','APPLE MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (241,'IO','BI-RITE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (242,'IP','OSBOURNES');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (243,'IQ','SAV-A-LOT');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (244,'IR','WALMART');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (245,'IS','HUNTERS HOMETOWN MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (246,'IT','LUNT\'S MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (247,'IU','TED\'S MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (248,'IV','GRAND UNION MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (249,'IW','PREMIUM GOLD');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (250,'IX','TAYLOR');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (251,'IY','THE FRESH MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (252,'IZ','PRAIRE GROVE FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (253,'JA','FOOD CITY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (254,'JB','FOOD KING');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (255,'JC','GIBBON');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (256,'JD','AMERICAN FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (257,'JE','ROXIE MARKETS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (258,'JF','FARMER JOHN');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (259,'JG','CARNICERIA LA AURORA');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (260,'JH','G & G EDDIES');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (261,'JI','A & P MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (262,'JJ','ADAMS SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (263,'JK','BIG Y WORLD CLASS MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (264,'JL','BLISS SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (265,'JM','CROWN SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (266,'JN','D & D MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (267,'JO','GARDINER\'S MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (268,'JP','GEISSLER\'S MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (269,'JQ','GNAZZO');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (270,'JR','GU FAMILY MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (271,'JS','HIGHLAND PARK MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (272,'JT','KINGSWOOD MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (273,'JU','RED APPLE SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (274,'JV','SCITICO MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (275,'JW','SHAW\'S SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (276,'JX','SHOP RITE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (277,'JY','STAFFORD FOOD CENTER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (278,'JZ','STOP & SHOP');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (279,'KA','ELLINGTON MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (280,'KB','THRIFTWAY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (281,'KC','TRADER JOE\'S GRASS FED BEEF');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (282,'KD','TRADER JOE\'S NATURAL BEEF');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (283,'KE','FOODMAXX');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (284,'KF','CREEKSTONE FARM');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (285,'KG','NATUREWELL');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (286,'KH','WIZER MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (287,'KI','MISTY ISLE FARM');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (288,'KJ','ROSEDA');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (289,'KK','LORENTZ MEAT-THOUSAND HILLS BEEF');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (290,'KL','FITZGERALD\'S FOOD MART');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (291,'KM','ANDY\'S SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (292,'KN','WEST-SIDE MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (293,'KO','THRIFTOWN');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (294,'KP','NATIONAL BEEF PACKING CO, EST. 208A');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (295,'KQ','NATIONAL BEEF PACKING CO, EST. 262');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (296,'KR','RUPRECHT CO.');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (297,'KS','ALIMENTS BRETON, INC.');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (298,'KT','SUNLAND');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (299,'KU','CHESTNUT & ENCINAL');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (300,'KV','NATURE\'S PROMISE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (301,'KW','INTERNATIONAL FARMER\'S MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (302,'KX','PLAINFIELD');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (303,'KY','COOKIN\' GOOD');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (304,'KZ','BC NATURAL FOODS LLC');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (305,'LA','J AND B GROUP, INC.');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (306,'LB','SEMN FOOD NETWORK');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (307,'LC','PASTURES APLENTY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (308,'LD','TSD SALES AND DISTRIBUTION');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (309,'LE','CARONNA\'S MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (310,'LF','PAT\'S MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (311,'LG','TOPS MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (312,'LH','GERESBECKS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (313,'LI','EDDIE\'S SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (314,'LJ','D\'ARTAGNAN');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (315,'LK','DON\'S SUPER VALUE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (316,'LL','TRUDEAU DISTRIBUTING');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (317,'LM','FARMINGTON FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (318,'LN','TRADER JOE\'S ORGANIC FREE RANGE CHICKEN');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (319,'LO','LUNARDI\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (320,'LP','PESCO FRESH FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (321,'LQ','LONG PRAIRIE PACKERS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (322,'LR','PAINTED HILLS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (323,'LS','BEIT BROS SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (324,'LT','LEBANON GREEN MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (325,'LU','BETTER VALU STORE  ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (326,'LV','TRI-TOWN FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (327,'LW','MOLLIE STONE\'S MARKETS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (328,'LX','NIMAN RANCH');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (329,'LY','FULTON VALLEY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (330,'LZ','SUPER MERCADO');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (331,'MA','AMERICA\'S CHOICE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (332,'MB','COUNTRY MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (333,'MC','NOEL\'S SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (334,'MD','ARGUELLO SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (335,'ME','PORTLAND COUNTY MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (336,'MF','THE DURHAM MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (337,'MG','SUNNYSIDE FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (338,'MH','AL\'S FOOD MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (339,'MI','ROSELAND');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (340,'MJ','CENTRAL MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (341,'MK','FRIGORIFICO LAS PIEDRAS S. A.');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (342,'ML','MARINA SUPERMARKET/MARINA FOOD');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (343,'MM','REAL FOOD COMPANY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (344,'MN','MASTER CATCH');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (345,'MO','PIEDMONT GROCERY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (346,'MP','MEADOWLAND FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (347,'MQ','VAL BEST');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (348,'MR','PAK N SAVE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (349,'MS','LUCKY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (350,'MT','STRICTLY KOSHER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (351,'MU','PUBLIX GREENWISE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (352,'MV','BUCKDEN VALUE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (353,'MW','FOOD 4 LESS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (354,'MX','GRANGER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (355,'MY','CARNECO FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (356,'MZ','KARNS QUALITY FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (357,'NA','REDNERS WAREHOUSE MARKETS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (358,'NB','OREGON FARM DAIRY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (359,'NC','STAUFFERS OF KISSEL HILL');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (360,'ND','WEISTER FOOD STORES');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (361,'NE','FOX\'S FOOD STORES');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (362,'NF','FOOD RITE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (363,'NG','ALDI');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (364,'NH','COUNTRY NATURAL BEEF');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (365,'NI','COLONIAL ESSEX MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (366,'NJ','TRADER JOE\'S GLATT KOSHER TURKEY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (367,'NK','TRADER JOE\'S ALL NATURAL');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (368,'NL','ANDRONICO\'S NATURAL CHICKEN');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (369,'NM','CHAIRMAN\'S RESERVE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (370,'NN','COUNTRY FRESH');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (371,'NO','COLEMAN ORGANIC');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (372,'NP','DAVID\'S KOSHER GROUND BEEF');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (373,'NQ','PRIVATE SELECTION ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (374,'NR','NATURE SELECT');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (375,'NS','MURPHY\'S FARM (WITH SMITHFIELD PROCESSING)');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (376,'NT','LEXINGTON MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (377,'NU','PRETTY BOY MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (378,'NV','EDDIE\'S SUPERMARKET, ROLAND PARK');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (379,'NW','T & J FOOD MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (380,'NX','GUILFORD FOOD CENTER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (381,'NY','AA SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (382,'NZ','WILLAMET VALLEY MEAT COMPANY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (383,'OA','NATURAL SOURCE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (384,'OB','GENE\'S FINE FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (385,'OC','NATURESOURCE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (386,'OD','JENNIE-O');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (387,'OE','SAM\'S CLUB');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (388,'OF','FIVE RIVERS FOOD GROUP');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (389,'OG','READINGTON FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (390,'OH','OLIVER\'S SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (391,'OI','TOWN PLOT SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (392,'OJ','ORGANICS, O ORGANICS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (393,'OK','SUPERWAY MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (394,'OL','NICA\'S MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (395,'OM','EAST STORE MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (396,'ON','COSTCO');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (397,'OO','MAPPLE TREE FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (398,'OP','LAMBS MARKETS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (399,'OQ','BRANDT BEEF');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (400,'OR','WEGMAN\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (401,'OS','ALLE PROCESSING');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (402,'OT','BRYAN\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (403,'OU','GROCERY OUTLET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (404,'OV','SEAFOOD CITY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (405,'OW','MASTER CUT');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (406,'OX','ALL NATURAL');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (407,'OY','HILTON SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (408,'OZ','RACE BROOK MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (409,'PA','H-MART ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (410,'PB','KROGER PRIVATE SELECTION ORGANIC');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (411,'PC','HARVESTLAND');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (412,'PD','HOLLY FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (413,'PE','CAL MART SUPER MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (414,'PF','MEAL MART');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (415,'PG','SOLOMON\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (416,'PH','JERRY\'S MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (417,'PI','TRIANGLE GROCERY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (418,'PJ','KAUNE FOODTOWN');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (419,'PK','LA MONTANITA CO-OP SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (420,'PL','THE MERC SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (421,'PM','RIVER CANYON RANCH');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (422,'PN','COUNTRY POST');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (423,'PO','KELLER\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (424,'PP','SHADY MAPLE FARM MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (425,'PQ','DUTCHWAY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (426,'PR','WEISSER\'S FOOD STORES');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (427,'PS','FPL FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (428,'PT','BG\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (429,'PU','KOSHER VALLEY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (430,'PV','JOHNSONVILLE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (431,'PW','DAKOTA FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (432,'PX','HEARTLAND FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (433,'PY','MARKET AT HIGHLANDTOWN');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (434,'PZ','TENDER CHOICE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (435,'RA','GRANDE FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (436,'RB','CARON\'S CORNER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (437,'RC','EVERYBODY\'S FOOD MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (438,'RD','DELANO\'S IGA');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (439,'RE','FIRST STREET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (440,'RF','SMART & FINAL');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (441,'RG','BLACKWELL ANGUS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (442,'RH','BOX & SAVE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (443,'RI','PECO');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (444,'RJ','FULL CIRCLE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (445,'RK','SILVER STATE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (446,'RL','TONY\'S MEATS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (447,'RM','EAST CENTER MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (448,'RN','MARKET OF CHOICE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (449,'RO','MORASCH MEATS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (450,'RP','KINGSVILLE MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (451,'RQ','MIDWEST RESERVE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (452,'RR','ESTANCIA');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (453,'RS','FARM HARVEST');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (454,'RT','LAMBS MARKETS, THUNDERING HOOVES');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (455,'RU','ALDI, FIT AND ACTIVE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (456,'RV','ACME');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (457,'RW','BOTTOM DOLLAR');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (458,'RX','CARNE MOLIDA DE PES');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (459,'RY','DARREN KAMPS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (460,'RZ','FIT/ACTIVE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (461,'SA','FRESH MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (462,'SB','GENUARDI\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (463,'SC','GIANT');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (464,'SD','LANCASTER BRAND');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (465,'SE','LEIDYS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (466,'SF','MASTER CHOICE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (467,'SG','NATURES PROMISE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (468,'SH','PATHMARK');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (469,'SI','SUPER FRESH');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (470,'SJ','SUPER VALUE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (471,'SK','WEGMANS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (472,'SL','WHITE OAK PASTURES');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (473,'SM','WHOLE FOODS MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (474,'SN','VALLEY NATURAL FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (475,'SO','MARY\'S ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (476,'SP','COUNTRY NATURAL');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (477,'SQ','PERDUE FIT AND EASY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (478,'SR','HEIDI\'S HENS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (479,'SS','STOLTZFUS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (480,'ST','CROPPERS SHURFINE MARKET - GT - STORE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (481,'SU','EMPIRE KOSHER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (482,'SV','SAFEWAY INC');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (483,'SW','TRADER JOE\'S ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (484,'SX','SHOWCASE FOODS (BEEF PATTIES DIST BY SHOWCASE FOODS)');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (485,'SY','CRESCENT');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (486,'SZ','FEDOR\'S MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (487,'TA','VON HANSON\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (488,'TB','GREAT RANGE ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (489,'TC','WILMAR MEAT');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (490,'TD','PINE MANOR');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (491,'TE','EVERETTS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (492,'TF','NORTHWEST BRAND');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (493,'TG','YOUNG\'S KENSINGTON MARKET ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (494,'TH','TEVA KOSHER FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (495,'TI','SAV-MOR BLOOMFIELD  MARKET INC.  ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (496,'TJ','KROGER PRIVATE SELECTION NATURAL');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (497,'TK','EATING RIGHT');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (498,'TL','MID ATLANTIC COUNTRY FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (499,'TM','MAPLE PLAIN FAMILY CENTER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (500,'TN','THE MARKET PLACE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (501,'TO','POLLO REAL');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (502,'TP','AVA, INC');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (503,'TQ','SCHNUCKS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (504,'TR','STERLING SILVER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (505,'TS','FRESH & GREENS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (506,'TT','MI RANCHITO BAY SIDE MARKET   ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (507,'TU','SEWARD CO-OP GROCERY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (508,'TV','HAGBERG\'S COUNTRY MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (509,'TW','BRISTOL DISCOUNT FOOD OUTLET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (510,'TX','RANCH MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (511,'TY','WIDMER SUPER MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (512,'TZ','MISSISSIPPI MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (513,'UA','DOUBLE R RANCH');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (514,'UB','BAYSIDE MARKET & DELI         ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (515,'UC','ANTONELLI\'S MEAT FISH & POULTRY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (516,'UD','MARTINS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (517,'UE','PANORAMA / PANORAMA, GRASS FED MEAT, ORGANIC');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (518,'UF','OPEN NATURE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (519,'UG','FRESH & EASY NEIGHBORHOOD MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (520,'UH','SO LOW GROCERY OUTLET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (521,'UI','SENTYRZ SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (522,'UJ','SIMPLE TRUTH ORGANIC');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (523,'UK','COVINGTON FARMS ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (524,'UL','ANGEL\'S FOOD MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (525,'UM','SPROUTS FARMERS MARKETS (SPROUTS)');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (526,'UN','SUPERVALU');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (527,'UO','PRICERITE ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (528,'UP','HALAL ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (529,'UQ','SHOP\'N SAVE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (530,'UR','AL-MAZRA\'AH HALAL');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (531,'US','NORTH AMERICAN ORGANIC BEEF, EST # 8268');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (532,'UT','DAKOTA BEEF');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (533,'UU','LAUER\'S SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (534,'UV','FERNDALE MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (535,'UW','MAXXVALUE (STORE/DISTRIBUTOR)   ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (536,'UX','LANGENSTEIN');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (537,'UY','POJOAQUE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (538,'UZ','AARON\'S BEST ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (539,'VA','CLAYTON\'S ORGANIC ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (540,'VB','NATURE\'S RANCHER ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (541,'VC','TOP FOOD & DRUG');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (542,'VD','PILGRIM\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (543,'VE','PRAIRIE LEGACY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (544,'VF','LAKEVIEW GROCERY IN NEW ORLEANS, LA');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (545,'VG','PCC / PCC NATURAL MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (546,'VH','KIRKWOOD');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (547,'VI','BISTRO MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (548,'VJ','DILLON\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (549,'VK','AMERICAN ORGANIC BEEF');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (550,'VL','EEL RIVER ORGANIC  ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (551,'VM','FOODMART (STORE AND DISTRIBUTOR)   ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (552,'VN','DRAEGERS   ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (553,'VO','MARKETIME FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (554,'VP','UWAJIMAYA');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (555,'VQ','DON\'S COUNTRY STORE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (556,'VR','FRANK\'S / FRANK\'S SUPER VALU ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (557,'VS','METROPOLITAN MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (558,'VT','OUR CERTIFIED');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (559,'VU','LESCHI MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (560,'VV','COSENTINO\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (561,'VW','BREAUX MART (SUPERMARKETS)');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (562,'VX','CHAVEZ SUPERMARKET ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (563,'VY','BARLOW TRAIL FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (564,'VZ','EAST GATE FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (565,'WA','STEW LEONARD\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (566,'WB','SOUTHERN HENS ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (567,'WC','VERDE FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (568,'WD','OUR PASTURES');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (569,'WE','LE GRAND');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (570,'WF','MATHERNE\'S SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (571,'WG','WAYNE FARMS ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (572,'WH','VERON\'S SUPERMARKET INC.');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (573,'WI','ZUPPARDO ECONOMICAL INC.');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (574,'WJ','RANCHER\'S LEGACY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (575,'WK','ANGUS PURE, NATURAL, GRASS FED');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (576,'WL','LISHMAN\'S CITY MARKET AT SLIDELL');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (577,'WM','HYVEE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (578,'WN','HARVEST FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (579,'WO','ANGUS PURE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (580,'WP','DIERBERGS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (581,'WQ','BERGAN\'S SUPER VALU');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (582,'WR','MAJORIA\'S SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (583,'WS','CASHIO\'S FOOD VILLA');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (584,'WT','CAGLE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (585,'WU','MARSHALL DURBIN');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (586,'WV','WOMMACK\'S MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (587,'WW','MEKONG RAINIER MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (588,'WX','ABC SUPERMARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (589,'WY','PROMENADE RED APPLE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (590,'WZ','SPRING CROSSING CATTLE CO');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (591,'XA','BURGER MAKER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (592,'XB','HARTER HOUSE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (593,'XC','GERBES');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (594,'XD','STONE\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (595,'XE','CHAPPAPEELA FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (596,'XF','BUTCHER\'S BEST');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (597,'XG','JAYS MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (598,'XH','LONG VALLEY RANCH');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (599,'XI','GREAUD FINE FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (600,'XJ','MONTLAKE BOULEVARD MARKET ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (601,'XK','JUST BARE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (602,'XL','MISTY KNOLL FARMS ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (603,'XM','SWEET TREE FARM ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (604,'XN','STONY BROOK ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (605,'XO','STAR MEATS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (606,'XP','THOUSAND HILLS CATTLE COMPANY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (607,'XQ','GOLD LEAF  ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (608,'XR','JUNIOR\'S FOODLAND');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (609,'XS','TOWN & COUNTRY MARKETS CHAIN (CENTRAL MARKET, BALLARD MARKET)');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (610,'XT','SWEETWATER CREEK');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (611,'XU','MUSILLAMI MEATS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (612,'XV','LOCAL HARVEST');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (613,'XW','SUNSET MARKET PLACE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (614,'XX','STEAKHOUSE ELITE/ KOBE BEEF AMERICA');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (615,'XY','PRIMAL (formerly THE MEAT HOUSE) ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (616,'XZ','STRAUB\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (617,'YA','MAR JAC / MAR JAC POULTRY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (618,'YB','SIMPLE TRUTH (NOT ORGNIC) ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (619,'YC','STRAUSS, FREE RAISED');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (620,'YD','NORTHWEST FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (621,'YE','MOSER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (622,'YF','TURKEY VALLEY FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (623,'YG','SUN FED RANCH');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (624,'YH','CHIAPPETTI');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (625,'YI','BOULDER NATURAL MEATS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (626,'YJ','COLEMAN NATURAL HAMPSHIRE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (627,'YK','HERITAGE FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (628,'YL','PREMIUM CUTS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (629,'YM','DORIGNAC\'S FOOD CENTER ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (630,'YN','GREG NORMAN SIGNATURE WAGYU/ WAGYU CATTLE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (631,'YO','EPICUREAN FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (632,'YP','NATURE RAISED FARM');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (633,'YQ','AMERICAN HOMESTEAD         ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (634,'YR','BARTELS FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (635,'YS','SIMPLY NATURE – ALL NATURAL FOOD');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (636,'YT','CRYSTAL RIVER MEATS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (637,'YU','JONES CREEK BEEF');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (638,'YV','AVON PRIME MEATS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (639,'YW','ACQUISTAPACE\'S (STEBEK\'S SUPERMARKET INC)');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (640,'YX','TENTON WATERS RANCH');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (641,'YY','FREEBIRD');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (642,'YZ','BLACK RIVER MEATS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (643,'ZA','HARDWICK BEEF');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (644,'ZB','HONEST WEIGHT FOOD CO-OP');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (645,'ZC','FOOD SOURCE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (646,'ZD','KEN\'S MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (647,'ZE','EL MEZQUITE MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (648,'ZF','FREDDIE\'S MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (649,'ZG','DRISKILL\'S FOODS ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (650,'ZH','WAGAR\'S GROCERY AND MEATS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (651,'ZI','ASIAN FOOD CENTER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (652,'ZJ','SCHWEID AND SONS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (653,'ZK','NATURE\'S RESERVE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (654,'ZL','JBS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (655,'ZM','SAM THE BUTCHER');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (656,'ZN','THE PIGGERY');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (657,'ZO','ROBERT\'S FOOD CENTER (FORMERLY, R.J.F INC.) ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (658,'ZP','MANCHESTER MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (659,'ZQ','BRINE\'S MEAT MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (660,'ZR','ENCINAL MARKET');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (661,'ZS','JAY INTERNATIONAL FOOD');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (662,'ZT','RANDALL FARMS ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (663,'ZU','PITMAN FAMILY FARMS ');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (664,'ZV','SCHUSTER MEAT');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (665,'ZW','AMICK FARMS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (666,'ZX','AUSTRALIAN GRASSFED CLASSIC BEEF');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (667,'ZY','SUPER H MART');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (668,'ZZ','SCHULTE\'S');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (669,'AAS','MI TIERRA FOODS');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (670,'AAT','EARTH FARE');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (671,'AAU','SPARTANNASH / SPARTAN NASH');
INSERT INTO narms_brand (ID, brand_code, brand_name) VALUES (672,'AAV','COMPART DUROC');
